### ISSUE TITLE
Significant CPU usage

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/explorer#109]
Doing nothing the explorer is using up 1/3rd of my processor activity. On refresh it's using up to 70%!

https://user-images.githubusercontent.com/105806603/176479356-f672e6d0-7e2d-4976-addd-7df35d24f6ff.mp4

**Comment by nop33** [comment]
I think it's related to the "waves" on the footer. When I go to a subpage of the explorer that doesn't use the waves, the CPU usage drops significantly.

**Comment by mvaivre** [comment]
Yeah as discussed with Lee, we can def optimize the rendering by avoiding drawing each pixel at each frame.
As a benchmark, It would be interesting to compare the cpu and gpu usage with another website using canvas animations.

**Comment by LeeAlephium** [comment]
>  draw a polyline instead of multiple separate lines.

This should help the situation I'd think...Doubtful it'll remove the issue due to there still being a line per pixel

> If too complicated

Never :sunglasses: 

Let me know when you'd like me to spend time :rocket:

**Comment by mvaivre** [comment]
Yes, your SVG idea sounds good to me @LeeAlephium ! 

Well, if you wanna spend an hour on it to see if this can be implemented, it would be great! Like that, we could release the website and an explorer update early next week.
