### ISSUE TITLE
Block Explorer Account for Analysts

### ISSUE THREAD

**Issue by nit27** [alephium/explorer#127]
### It would be great if people can create accounts from the Explorer in order to:
- analyse transactions
- address watch lists
- address labels
- email notification when watch lists have transactions.
- notes
- CSV export
### reference
- [etherscan](https://etherscan.io/login)

**Comment by mvaivre** [comment]
Hi there! Thanks for the suggestion.

As far as I can see, we won't want to manage and store user accounts on our side. 
It would probably be more appropriate if the community would develop such kind of services, on top of what we offer.

CSV export for addresses is coming though! ;)
