### ISSUE TITLE
Consider ejecting from CRA

### ISSUE THREAD

**Issue by nop33** [alephium/explorer#129]
Today I noticed many PRs from dependabot trying to upgrade react-scripts from 4.0.3 to 5.0.1. Doing that, however, breaks the build because react-scripts 5.0.1 uses webpack 5 and webpack 5 does not polyfill node modules like webpack 4 did. This means we'd need to override the weback config of create-react-app, and the only way to do that is to eject:

- https://github.com/facebook/create-react-app/issues/11756#issuecomment-1241853345
- https://alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5

Let's evaluate whether we really need to do that or not.

**Comment by mvaivre** [comment]
Thanks for the heads-up. I've investigated the issue a bit on my side, and I'd rather eject or migrate away from CRA at this point. 
I believe that we can find more lightweight, better maintained & faster build tools now.

IMO one interesting project that is standing out from the crowd is [_Vite_](https://vitejs.dev/).

https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite

**Comment by mvaivre** [comment]
I've ejected to Vite in e426d2e98e0f972fe7a9f89c8cc0b9e21e9d442b
