### ISSUE TITLE
Fix Vite.js build

### ISSUE THREAD

**Issue by mvaivre** [alephium/explorer#144]
```Cannot read properties of undefined (reading 'from')```

Since linked to the `safe-buffer` package and node.js polyfills...

https://github.com/vitejs/vite/issues/7384

https://github.com/feross/safe-buffer/issues/30

We should maybe analyse how those crypto fn are used through our sdk. In theory, NodeJS functions shouldn't be required to run in the browser.

**Comment by nop33** [comment]
When I manually edit the `node_modules/@alephium/sdk/package.json` file and make the following change, I don't get the error anymore:

```
  "exports": {
    ".": "./dist/lib/index.js"
  },
```

to:

```
  "exports": {
    ".": "./dist/alephium.min.js"
  },
```

So, we somehow have to tell Vite to pick up that file.

**Comment by mvaivre** [comment]
Yes! Well done. 
That's what I thought. I don't think that it's specifically related to Vite, because we had the same issue before with CRA, which needed the polyfills for our SDK to work. 
It seems like the field `"browser": "dist/alephium.min.js"` doesn't work as expected. According to [npm docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#browser):

> If your module is meant to be used client-side the browser field should be used instead of the main field. 

What I understand is that if we keep the `main` field, it will be preferred and the `browser` field will be ignored.

**Comment by nop33** [comment]
FWIW, here's my research on module systems for the SDK: https://github.com/orgs/alephium/teams/front-end/discussions/5

Our goals were:

> Make sure that our SDK can be used in all of the following environments, by default:
> 
> - NodeJS applications (oldest Maintenance LTS version of NodeJS that hasn't reached EOL)
> - Modern browsers (no IE)
> - Modern frontend frameworks (ex: React, Vue)
> - Mobile apps (React Native)

**Comment by mvaivre** [comment]
> > What I understand is that if we keep the main field, it will be preferred and the browser field will be ignored.
> 
> I tried adding `dist/alephium.min.js` in the `main` field, but it didn't fix the problem. It seems that the following was still the prefered option:
> 
> ```
>   "exports": {
>     ".": "./dist/lib/index.js"
>   },
> ```

You mean 

```
  "exports": {
    ".": "./dist/alephium.min.js"
  }
```

?

Interesting read about the exports field: https://medium.com/swlh/npm-new-package-json-exports-field-1a7d1f489ccf

**Comment by nop33** [comment]
No, I meant what I wrote :) Leaving the `exports` untouched and changing only the `main` and `browser` to be `dist/alephium.min.js` did not fix the problem. So it would seem that `exports` is always preferred. I can try to remove it and see what happens then.

**Comment by mvaivre** [comment]
You tried removing `main` and keeping only `browser`?

**Comment by nop33** [comment]
The problem was that the `exports` field was taking precedence over the `main` and `browser` fields. The solution to the problem was to add the following (see https://github.com/alephium/js-sdk/pull/132):

```json
"exports": {
    ".": {
      "browser": "./dist/alephium.min.js",
      "default": "./dist/lib/index.js"
    }
}
```

Based on the NodeJS docs:
> For new packages targeting the currently supported versions of Node.js, the "exports" field is recommended. For packages supporting Node.js 10 and below, the "main" field is required. If both "exports" and "main" are defined, the "exports" field takes precedence over "main" in supported versions of Node.js.
> 
> When writing a new package, it is recommended to use the "exports" field.

Even though removing `main` and `browser` and only leaving `exports` worked well when testing node and browser environments, it didn't work in React Native environment. So, the `main` and `browser` fields remain.
