### ISSUE TITLE
More granular loading of address data

### ISSUE THREAD

**Issue by mvaivre** [alephium/explorer#198]
Call `/addresses/<addr>/balance` and `/addresses/<addr>/total-transactions` instead of just `/addresses/<addr>` to get the data.

That's 2 calls instead of 1, that would allow to quickly show the balance, the fiat price etc and just let the nb of transaction with a loader.
Don't wait for data to be loaded to display the assets table.

Use a large address like [1DKWCEc9HjhchKoMCMA4J1nbNGNjrAoPFnkcgA1w6h7jh](https://explorer.alephium.org/addresses/1DKWCEc9HjhchKoMCMA4J1nbNGNjrAoPFnkcgA1w6h7jh) for testing.

**Comment by nop33** [comment]
I believe there's an open PR for that: https://github.com/alephium/explorer/pull/193/commits/4ce6090da83cf61badfeb58784cb092352cf5ac2
