### ISSUE TITLE
mainnet vs. testnet distinction

### ISSUE THREAD

**Issue by ferdinandhodl** [alephium/explorer#26]
UI/UX: related to issue #24 and #25, could you please also add the switch to the [testnet](https://testnet.alephium.org) site, in order to be able to switch back to [mainnet](https://explorer.alephium.org)?
<img width="278" alt="mainnet switch" src="https://user-images.githubusercontent.com/83892720/141786127-1fe1cc53-8f69-4eb5-9547-5c41d90e821b.png">
vs.
<img width="255" alt="testnet switch" src="https://user-images.githubusercontent.com/83892720/141786129-216f33fe-2748-4e9f-96cc-8e1b1a4e68b4.png">

Further it would be great to mention the network in the header of the page, e.g. "Testnet Explorer" and "Mainnet Explorer" to visually distinguish the two.

<img width="238" alt="Alephium explorer head" src="https://user-images.githubusercontent.com/83892720/141786337-fefcb2a6-674d-4a71-984b-eb2ee5287aa5.png">

**Comment by mvaivre** [comment]
The switch is now available on both the testnet and mainnet explorers.
I'll create a new task to make the switch more visible (better visual distinction between both environments). Thanks @ferdinandhodl!
