### ISSUE TITLE
CSV export function

### ISSUE THREAD

**Issue by phrichner** [alephium/explorer#41]
Create a function to export the transactions of an address into a CSV file. Similar feature like already available on etherscan.io and other explorers.

It would be great to have the following information included:
Txhash - Blockno - UnixTimestamp - DateTime - From address - To address - ContractAddress - ValueIn - ValueOut - TxnFee(ALPH) - TxnFee(USD) - Historical$Price/ALPH - Status - ErrCode - Method

The UnixTimestamp would not be required if in the DateTime information the information about the Time zone is included.

**Comment by mvaivre** [comment]
@tdroxler How hard would it be possible to query TXs not only by pages but also using a from/to machanism?

**Comment by tdroxler** [comment]
quite easy I would say, but we need to think if we allow etiher pagination or from/to on the same endpoint, could be nice

**Comment by mvaivre** [comment]
yes, that's what I had in mind. Ideally 1 endpoint, multiple query range strategies 👌

**Comment by polarker** [comment]
How is the design on Etherscan?

**Comment by mvaivre** [comment]
> How is the design on Etherscan?

You can take a look by clicking on "Download CSV export" at the bottom of a TX list in the address view.
Example: https://etherscan.io/exportData?type=address&a=0x530061b4de80278ebc15547f662da6b5bf3c58e0

It's actually after seing how they do it that I decided to formulate the question above. Their flow is: go to address, click the button => enter the from/to params => validate captcha => download the CSV.

**Comment by lf94** [comment]
> validate captcha => download the CSV

I think we could do better by avoiding this simply by only exporting the visible transactions. Etherscan must do this to prevent abuse on addresses with unfathomable numbers of transactions.

**Comment by mvaivre** [comment]
> ... by only exporting the visible transactions.

This would greatly limit the usefulness of the feature. I see this used a lot for tax / accounting perspective, where you need to export a full year worth of data.

**Comment by lf94** [comment]
I would just like to avoid a dependency on an external captcha service. Maybe we can use a self-hosted solution.

**Comment by mvaivre** [comment]
We can start without any rate limiting solution, then act subsequently once / if we hit performance problems.

**Comment by lf94** [comment]
> we will need to look into fetching the market price to feed the desktop and mobile wallets at one point

Would be cool to use a price oracle. The oracle (just a program) gets the price from gate.io (or other sources, is configurable and can be aggregated) and posts it on the Alephium network. Then our wallets can fetch this permanent information quite easily and not rely on centralized entities for historical price data (and as exchanges grow, the source becomes less centralized). It can be very low resolution price data; once per day posting.

**Comment by mvaivre** [comment]
While I obviously love the idea of a decentralised solution (low resolution price data would work for the explorer's CSV export feature), I don't think this would fit the requirements for showing the price data in our wallets. A lot of users check the price multiple times a day, to follow its short term swings, and hence need higher refresh rates. But this is a discussion to have somewhere else (explorer backend? I'm discussing it with Thomas).

**Comment by lf94** [comment]
Ah yeah, for those day traders, it's useless.

**Comment by mvaivre** [comment]
This feature is mentioned by more and more users, let's bump the priority up a bit. 
@tdroxler could you consider add this to your backlog?
I'm working on some mockups.
cc/ @lf94 :)

**Comment by nop33** [comment]
Yet another request came for this issue on Discord:

> Any chance we can get a CSV export on the alephium explorer site for those of us who need to import transactions into our tax software? 🙂 
> basic tx info such as “utc date time”, “send address”,”receive address”,”txid”,”token name”,”token amount”, etc
Similar to what etherscan, snowtrace, etc do

@tdroxler @mvaivre let's consider re-ordering our priorities

**Comment by polarker** [comment]
`vidmaster` from Discord mentioned this website: https://stake.tax/. It looks like a great source of inspiration.

**Comment by mvaivre** [comment]
@tdroxler Let's talk about this task when you're available.

@polarker Thanks for sharing this. Stake.tax seems like a super nice tool based on the few min spent playing with it.

**Comment by mvaivre** [comment]
We'll be using [reCAPTCHA v3](https://developers.google.com/recaptcha/docs/v3) which doesn't induce any user friction.

**Comment by mvaivre** [comment]
Update after talking with @tdroxler and @killerwhile :
- We'll start with rate-limiting this specific endpoint, as proposed before. Green lighting users based on Captcha can be a bit complicated because of our distributed infra (need to broadcast the "greenlight information" through our different instances). Let's start simple and add complexity when (if) needed.
- We may propose different export formats like stake.tax is doing. I'll investigate if this is useful, and if so, which tax services we're targeting. 
- The endpoint will probably directly serve CSV files. Thomas is looking into it.
- I've started to work on mockups, will be done soon. 

<img width="542" alt="image" src="https://user-images.githubusercontent.com/6715943/197467531-8e2321dd-fb91-48b0-b61c-bf92825e20d8.png">

**Comment by mvaivre** [comment]
Closing this as the first version has been shipped. Feel free to open a new issue to talk about more options (format etc.) if needed.
