### ISSUE TITLE
Ensure compatibility with rc releases of node, explorer backend, and alephium-js

### ISSUE THREAD

**Issue by nop33** [alephium/explorer#63]
- node: [v1.3.0-rc6](https://github.com/alephium/alephium/tree/v1.3.0-rc6)
- explorer-backend: [v1.6.0-rc2](https://github.com/alephium/explorer-backend/tree/v1.6.0-rc2)
- alephium-js: ~~[v1.1.3-rc0](https://github.com/alephium/alephium-js/tree/1.1.3-rc0)~~ v1.20-rc1

**Comment by polarker** [comment]
@nop33 We will need to make a new candidate release for "alephium-js": `v1.2.0-rc1`. I did not make the release as I thought you guys would like to do it. `v1.1.3-rc0` was released earlier by me for testing the new release workflow.

**Comment by nop33** [comment]
Ah, ok, I'll take care of upgrading the schemas and creating a new rc, thanks for letting me know
