### ISSUE TITLE
Load data only when browser tab is in view

### ISSUE THREAD

**Issue by mvaivre** [alephium/explorer#80]
Avoid useless server loads by fetching only when browser tab is active.

**Comment by lf94** [comment]
IIRC this is quite simple to do.

**Comment by mvaivre** [comment]
Wanna do it @lf94? Feel free to assign yourself, would be great 🙌 👌

**Comment by lf94** [comment]
* https://www.npmjs.com/package/@react-hook/timeout
* https://www.joshwcomeau.com/snippets/react-hooks/use-timeout/#explanation

Going to do a small experiment.

**Comment by lf94** [comment]
I discovered we're already using a `useInterval` hook taken from somewhere (https://www.joshwcomeau.com/snippets/react-hooks/use-interval/ references Dan Abramov as the original author). The implementation still uses `setInterval` internally so it's not an option.

We'll use the hook.
